#!/bin/bash

# Script de déploiement rapide sur Render.com
# Usage: bash deploy-render.sh

echo "🚀 Préparation du déploiement SSL Cert Monitor sur Render.com"
echo ""
echo "Prérequis:"
echo "1. Compte Render.com créé (https://render.com)"
echo "2. Repository GitHub connecté"
echo ""
echo "Options de déploiement:"
echo ""
echo "Option 1: Déploiement automatique via Blueprint (RECOMMANDÉ)"
echo "=================================================="
echo "1. Aller sur: https://render.com/deploy?repo=https://github.com/alex-dembele/ssl-certs-monitor"
echo "2. Connecter GitHub si nécessaire"
echo "3. Revérifier les paramètres"
echo "4. Cliquer 'Deploy'"
echo ""
echo "Option 2: Déploiement manuel"
echo "============================"
echo "1. Aller sur https://render.com"
echo "2. Dashboard → New +"
echo ""
echo "Pour le Backend API:"
echo "  - Type: Web Service"
echo "  - Runtime: Python 3.10"
echo "  - Build Command: pip install -r requirements.txt"
echo "  - Start Command: uvicorn main:app --host 0.0.0.0 --port 8000"
echo "  - Root Dir: backend"
echo ""
echo "Pour le Frontend:"
echo "  - Type: Web Service"
echo "  - Runtime: Node 18"
echo "  - Build Command: npm install && npm run build"
echo "  - Start Command: npm start"
echo "  - Root Dir: frontend"
echo "  - Env Var: NEXT_PUBLIC_API_URL=https://ssl-cert-monitor-api.onrender.com"
echo ""
echo "Pour le Cron Worker:"
echo "  - Type: Background Worker"
echo "  - Runtime: Python 3.10"
echo "  - Build Command: pip install -r requirements.txt"
echo "  - Start Command: python cron_job.py"
echo "  - Root Dir: backend"
echo ""
echo "✅ Une fois les 3 services déployés, vous aurez:"
echo "   - Frontend: https://ssl-cert-monitor-frontend.onrender.com"
echo "   - Backend API: https://ssl-cert-monitor-api.onrender.com"
echo "   - Cron: En arrière-plan"
